version: '3.9'

services:
  api-1:
    image: juninhocb/rinhabackend2024q1:latest
    hostname: api-1
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/db_rinha
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - app-network
    depends_on:
      mysql-db:
        condition: service_healthy
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "150MB"

  api-2:
    image: juninhocb/rinhabackend2024q1:latest
    hostname: api-2
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/db_rinha
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - app-network
    depends_on:
      mysql-db:
        condition: service_healthy
    ports:
      - "8081:8080"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "150MB"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-1
      - api-2
    ports:
      - "9999:9999"
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '10MB'

  mysql-db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_rinha
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root -proot" ]
      interval: 300s
      timeout: 5s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '240MB'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge